project.module=build.jenesis

project.name=Jenesis
project.description=A build tool for Java projects, written and configured in Java itself.
project.url=https://github.com/raphw/jenesis
license.name=Apache-2.0
license.url=https://www.apache.org/licenses/LICENSE-2.0.txt
developer.id=raphw
developer.name=Rafael Winterhalter
developer.email=rafael.wth@gmail.com
scm.connection=scm:git:https://github.com/raphw/jenesis.git
scm.developerConnection=scm:git:git@github.com:raphw/jenesis.git
scm.url=https://github.com/raphw/jenesis
