name: Test Jenesis Tool

on:
  push:
    branches: [main]
  pull_request:

jobs:
  manual:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build: [Manual, Maven, Minimal, Modular, ModularToMaven, Modules]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up JDK 25
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: '25'

      - name: ${{ matrix.build }}.java
        run: java build/${{ matrix.build }}.java

  project:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        layout: [auto, maven, modular, modular_to_maven]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up JDK 25
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: '25'

      - name: Project layout ${{ matrix.layout }}
        run: java -Djenesis.project.layout=${{ matrix.layout }} build/jenesis/Project.java stage
